export const DATA_LOADED = "DATA_LOADED";
export const LOADING = "LOADING";
export const ADD_TO_CART = "ADD_TO_CART";
export const FETCH_CART_ITEMS = "FETCH_CART_ITEMS";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADD_QUANTITY = "ADD_QUANTITY";
export const SUBTRACT_QUANTITY = "SUBTRACT_QUANTITY";